---
title: "Data_Import"
output: html_document
date: "2023-04-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Libraries
library(tidyverse)
library(dplyr)
library(haven)
library(ggplot2)
## long / wide data
library(tidyr)
```

## Import data
Read in the dataset. 
```{r}
df <- read_sav("~/Desktop/Coding/data/Mothership_DV.sav")
view(df)
Mothership<-select(df,ID1:Sexuality_1,MDD_C:Day40_CUXOS)
```
## Rename and Recode variables 
We can change the current variables to make them easier to interpret. 
```{r}
#recode varaibles

Mothership <- mutate(Mothership, 
                     DC_status_1 = as.factor(DC_status_1),
                     DC_status_1 = recode(DC_status_1,
                                          "1"="Complete",
                                          "2"="Nearly Complete",
                                          "3"="Insurance",
                                          "4"="Nonatteneance",
                                          "5"="Inappropriate",
                                          "6"="Inpatient",
                                          "7"="Withdrew",
                                          "8"="Dissatisfaction",
                                          "9"="Other"),
                     Education_1 = as.factor(Education_1),
                     Education_1 = recode(Education_1,
                                          "1"="<Grade 12",
                                          "2"="HS Diploma",
                                          "3"="GED",
                                          "4"="Some College",
                                          "5"="Associates Degree",
                                          "6"="Bachelors Degree",
                                          "7"="Some Grad School",
                                          "8"="Grad Degree"),
                     Gender_1 = as.factor(Gender_1),
                     Gender_1 = recode(Gender_1,
                                       "0"="Female",
                                       "1"="Male",
                                       "2"="Non-Binary",
                                       "3"="Other",
                                       "4"="Unknown"),
                     Relationship_1 = as.factor(Relationship_1),
                     Relationship_1 = recode(Relationship_1,
                                             "0"="Married",
                                             "1"="Cohabitating",
                                             "2"="Widowed",
                                             "3"="Separated",
                                             "4"="Divorced",
                                             "5"="Never Married"),
                     Sexuality_1 = as.factor(Sexuality_1),
                     Sexuality_1 = recode(Sexuality_1,
                                          "1"="Straight",
                                          "2"="Gay",
                                          "3"="Bisexual",
                                          "4"="Other"),
                     IPT_track_1 = as.factor(IPT_track_1),
                     IPT_track_1 = recode(IPT_track_1,
                                          "0"="General",
                                          "1"="Trauma",
                                          "2"="Young Adult",
                                          "3"="BPD"),
                     Race_1 = as.factor(Race_1),
                     Race_1 = recode(Race_1,
                                     "0"="White",
                                     "1"="Black",
                                     "2"="Hispanic",
                                     "3"="Asian",
                                     "4"="Portugese",
                                     "5"="Other"),
                     Education_1 = as.factor(Education_1),
                     Education_1 = recode(Education_1,
                                      "0"="<Grade 6", 
                                      "1"="Grades 7-12",
                                      "2"="HS Diploma", 
                                      "3"="GED",
                                      "4"="Some College",
                                      "5"="Associates Degree",
                                      "6"="Bachelors Degree",
                                      "7"="Some Grad School",
                                      "8"="Grad Degree"),
  
       #Lets make some new variables 
                     Duration = as.factor(
                       ifelse(Days_complete_1>0 & Days_complete_1 <=5, "1-5",
                       ifelse(Days_complete_1>5 & Days_complete_1 <=10, "6-10",
                       ifelse(Days_complete_1>10 & Days_complete_1 <=15, "11-15", "16+"
                              )))))
# Disorder subtypes 
# Mood Disorders
# Anxiety Disorders
# Obsessive Compusive Disorders
# Personality Disorders
# Substance Use Disorders
# Trauma related disorders
# Psychotic Disorders
# Eating Disorders

                      
                     
                     
                     
#Extract Year From Intake Date
#Convert to Date
library("lubridate")
Mothership$Intake_1<-mdy(Mothership$Intake_1,locale = "en_US.UTF-8")
Mothership$TxYear<-as.numeric(format(Mothership$Intake_1,"%Y"))

Mothership<-mutate(Mothership,
                   TxYear = as.factor(TxYear),
                   TxYear = recode(TxYear,
                                   "1582"="2014",
                                   "2021"="2020",
                                   "2022"="2020"))

```

```{r}
### Bar Chart for Discharge Status ###
plot(Mothership2$DC_status_1)

ggplot(data = subset(Mothership, !is.na(DC_status_1)), mapping = aes(x = DC_status_1))+
  geom_bar(color = "black",fill="darkgreen")+
  ggtitle("Frequency of Treatment Discharge Status") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  xlab("Discharge Status") +
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  scale_y_continuous(name = "Frequency",limits=c(0,6000))

### Bar Chart for Education Status ###

ggplot(data = subset(Mothership, !is.na(Education_1)),mapping = aes(x = Education_1))+
  geom_bar(color = "black",fill="darkred")+
  ggtitle("Frequency of Education Level") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  xlab("Education Level")+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  scale_y_continuous(name = "Frequency",limits=c(0,3000))
```

## Pie Chart For Education Status 
```{r}
#Create Table and Data Frame
Education<-table(Mothership$Education_1)
Education_df<-as.data.frame(Education)
Education_df

#Rename Columns
colnames(Education_df)[1]="Category"
colnames(Education_df)[2]="Frequency"


Education_df$Category=recode(Education_df$Category,
                             "0"="<Grade 6", 
                             "1"="Grades 7-12",
                             "2"="HS Diploma", 
                             "3"="GED",
                             "4"="Some College",
                             "5"="Associates Degree",
                             "6"="Bachelors Degree",
                             "7"="Some Grad School",
                             "8"="Grad Degree")

ggplot(data = Education_df, mapping = aes(x="", y=Frequency, fill=Category))+
  geom_bar(stat="Identity",width=1,color="white")+
  coord_polar("y",start=0)+
  theme_void()
```


## Depression Treatment Progress Charts

```{r}
Mothership_Long <- gather(Mothership,rm,CUDOS,Day1_CUDOS:Day40_CUDOS,factor_key = "T")
Mothership_Long <- Mothership_Long[order(Mothership_Long$ID1),]

#Create a Time Variable
Mothership_Long$TxDay <- NA
Mothership_Long$TxDay[Mothership_Long$rm=="Day1_CUDOS"]<-1
Mothership_Long$TxDay[Mothership_Long$rm=="Day2_CUDOS"]<-2
Mothership_Long$TxDay[Mothership_Long$rm=="Day3_CUDOS"]<-3
Mothership_Long$TxDay[Mothership_Long$rm=="Day4_CUDOS"]<-4
Mothership_Long$TxDay[Mothership_Long$rm=="Day5_CUDOS"]<-5
Mothership_Long$TxDay[Mothership_Long$rm=="Day6_CUDOS"]<-6
Mothership_Long$TxDay[Mothership_Long$rm=="Day7_CUDOS"]<-7
Mothership_Long$TxDay[Mothership_Long$rm=="Day8_CUDOS"]<-8
Mothership_Long$TxDay[Mothership_Long$rm=="Day9_CUDOS"]<-9
Mothership_Long$TxDay[Mothership_Long$rm=="Day10_CUDOS"]<-10
Mothership_Long$TxDay[Mothership_Long$rm=="Day11_CUDOS"]<-11
Mothership_Long$TxDay[Mothership_Long$rm=="Day12_CUDOS"]<-12
Mothership_Long$TxDay[Mothership_Long$rm=="Day13_CUDOS"]<-13
Mothership_Long$TxDay[Mothership_Long$rm=="Day14_CUDOS"]<-14
Mothership_Long$TxDay[Mothership_Long$rm=="Day15_CUDOS"]<-15
Mothership_Long$TxDay[Mothership_Long$rm=="Day16_CUDOS"]<-16
Mothership_Long$TxDay[Mothership_Long$rm=="Day17_CUDOS"]<-17
Mothership_Long$TxDay[Mothership_Long$rm=="Day18_CUDOS"]<-18
Mothership_Long$TxDay[Mothership_Long$rm=="Day19_CUDOS"]<-19
Mothership_Long$TxDay[Mothership_Long$rm=="Day20_CUDOS"]<-20

#Create a New Data Set with an Average Depression Variable
Mothership_Mean_CUDOS<-Mothership_Long %>%
  group_by(TxDay) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))
```


```{r}
#Plot the Depression Mean for Full Sample
ggplot(data=Mothership_Mean_CUDOS,aes(x=TxDay,y=mean_CUDOS))+
  geom_line(size=1,color="#0065A3")+
  geom_point(color="#0065A3")+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  ggtitle("Mean Depression Severity During Partial Hospitalization")+
  scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))+
  scale_y_continuous(name="Depression Severity",limits=c(20,35,by=5))+
  theme(panel.background=NULL) +
  geom_vline(xintercept = 5, color = "#BB9D00",alpha =.5)+
  geom_vline(xintercept = 8, color = "orange",alpha =.5)+
  geom_vline(xintercept = 13, color = "red",alpha =.5)+
  annotate("text", x = 5, y = 34, label = "Q1") +
  annotate("text", x = 8, y = 34, label = "Mean") +
  annotate("text", x = 13, y = 34, label = "Q3") 

ggplot(Mothership, aes(Days_complete_1))+
  geom_density()+
  scale_x_continuous(limits=c(0,20)) +
  labs(
    title="Quantity of discharges Per Treatment Day")


```

### plot means based upon duration group membership 
```{r}
ggplot(Mothership, aes(x = Duration, y = Days_complete_1)) +
  geom_violin()+
  geom_boxplot(width=0.1, color="blue", alpha=0.2)

Mothership_duration_CUDOS<-Mothership_Long %>%
  group_by(TxDay,Duration) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

```


```{r}
#plot depression mean with each group

Mothership_Mean_CUDOS<-Mothership_Long %>%
  group_by(Duration,TxDay) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))


Mothership_duration_CUDOS<-Mothership_Mean_CUDOS[1:83,]
#delete weird Na values and put NA for values
Mothership_duration_CUDOS[6:20,3] = NA
Mothership_duration_CUDOS[37:41,3] = NA
Mothership_duration_CUDOS[74:83,3] = NA
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-21),]
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-41),]
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-61),]
Mothership_duration_CUDOS

ggplot(data=Mothership_duration_CUDOS,aes(x=TxDay,y=mean_CUDOS,group=Duration,color=Duration))+
  geom_line(size=1)+
  geom_point()+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  ggtitle("Mean Depression Severity During Partial Hospitalization")+
  scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))+
  scale_y_continuous(name="Depression Severity",limits=c(15,40,by=5))+
  scale_color_manual(values=c("#BB9D00","red",
                              "darkred","orange"))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())+
  geom_vline(xintercept = 5,alpha =.25)+
  geom_vline(xintercept = 8,alpha =.25)+
  geom_vline(xintercept = 13,alpha =.25)+
  annotate("text", x = 5, y = 39, label = "Q1") +
  annotate("text", x = 8, y = 39, label = "Mean") +
  annotate("text", x = 13, y = 39, label = "Q3") 



```



