---
title: "Depression_Vis"
output: html_document
date: "2023-04-03"
---

```{r setup, include=FALSE}
# Libraries 
library(tidyverse)
library(dplyr)
library(haven)
library(ggplot2)
library(tidyr)
library("lubridate")

#Data
Mothership<-read.csv("~/Desktop/Coding/data/Mothership_Vis.csv")
Mothership<-mutate(Mothership,
      DC_status_1 = as.factor(DC_status_1),
      Education_1 = as.factor(Education_1),
      Gender_1 = as.factor(Gender_1),
      Relationship_1 = as.factor(Relationship_1),
      Sexuality_1 = as.factor(Sexuality_1),
      IPT_track_1 = as.factor(IPT_track_1),
      Race_1 = as.factor(Race_1),
      Education_1 = as.factor(Education_1),
      Duration = as.factor(Duration),
      TxYear = as.factor(TxYear)
      )
```

## Depression Treatment Progress Charts

```{r}
Mothership_Long <- gather(Mothership,rm,CUDOS,Day1_CUDOS:Day40_CUDOS,factor_key = "T")
Mothership_Long <- Mothership_Long[order(Mothership_Long$ID1),]

#Create a Time Variable
Mothership_Long$TxDay <- NA
Mothership_Long$TxDay[Mothership_Long$rm=="Day1_CUDOS"]<-1
Mothership_Long$TxDay[Mothership_Long$rm=="Day2_CUDOS"]<-2
Mothership_Long$TxDay[Mothership_Long$rm=="Day3_CUDOS"]<-3
Mothership_Long$TxDay[Mothership_Long$rm=="Day4_CUDOS"]<-4
Mothership_Long$TxDay[Mothership_Long$rm=="Day5_CUDOS"]<-5
Mothership_Long$TxDay[Mothership_Long$rm=="Day6_CUDOS"]<-6
Mothership_Long$TxDay[Mothership_Long$rm=="Day7_CUDOS"]<-7
Mothership_Long$TxDay[Mothership_Long$rm=="Day8_CUDOS"]<-8
Mothership_Long$TxDay[Mothership_Long$rm=="Day9_CUDOS"]<-9
Mothership_Long$TxDay[Mothership_Long$rm=="Day10_CUDOS"]<-10
Mothership_Long$TxDay[Mothership_Long$rm=="Day11_CUDOS"]<-11
Mothership_Long$TxDay[Mothership_Long$rm=="Day12_CUDOS"]<-12
Mothership_Long$TxDay[Mothership_Long$rm=="Day13_CUDOS"]<-13
Mothership_Long$TxDay[Mothership_Long$rm=="Day14_CUDOS"]<-14
Mothership_Long$TxDay[Mothership_Long$rm=="Day15_CUDOS"]<-15
Mothership_Long$TxDay[Mothership_Long$rm=="Day16_CUDOS"]<-16
Mothership_Long$TxDay[Mothership_Long$rm=="Day17_CUDOS"]<-17
Mothership_Long$TxDay[Mothership_Long$rm=="Day18_CUDOS"]<-18
Mothership_Long$TxDay[Mothership_Long$rm=="Day19_CUDOS"]<-19
Mothership_Long$TxDay[Mothership_Long$rm=="Day20_CUDOS"]<-20

#Create a New Data Set with an Average Depression Variable
Mothership_Mean_CUDOS<-Mothership_Long %>%
  group_by(TxDay) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))
```


```{r}
#Plot the Depression Mean for Full Sample
ggplot(data=Mothership_Mean_CUDOS,aes(x=TxDay,y=mean_CUDOS))+
  geom_line(size=1,color="#0065A3")+
  geom_point(color="#0065A3")+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  ggtitle("Mean Depression Severity During Partial Hospitalization")+
  scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))+
  scale_y_continuous(name="Depression Severity",limits=c(20,35,by=5))+
  theme(panel.background=NULL) +
  geom_vline(xintercept = 5, color = "#BB9D00",alpha =.5)+
  geom_vline(xintercept = 8, color = "orange",alpha =.5)+
  geom_vline(xintercept = 13, color = "red",alpha =.5)+
  annotate("text", x = 5, y = 34, label = "Q1") +
  annotate("text", x = 8, y = 34, label = "Mean") +
  annotate("text", x = 13, y = 34, label = "Q3") 

ggplot(Mothership, aes(Days_complete_1))+
  geom_density()+
  scale_x_continuous(limits=c(0,20,by=1)) +
  labs(
    title="Quantity of discharges Per Treatment Day")
```

### plot means based upon duration group membership 

```{r}
#plot depression mean with each group

# New dataset for the treatment duration depression plot
Mothership_Mean_CUDOS<-Mothership_Long %>%
  group_by(Duration,TxDay) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

Mothership_duration_CUDOS<-Mothership_Mean_CUDOS[1:83,]
#delete weird Na values and put NA for values
Mothership_duration_CUDOS[6:20,3] = NA
Mothership_duration_CUDOS[37:41,3] = NA
Mothership_duration_CUDOS[74:83,3] = NA
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-21),]
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-41),]
Mothership_duration_CUDOS<-Mothership_duration_CUDOS[(-61),]
Mothership_duration_CUDOS

ggplot(data=Mothership_duration_CUDOS,aes(x=TxDay,y=mean_CUDOS,group=Duration,color=Duration))+
  geom_line(size=1)+
  geom_point()+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  ggtitle("Mean Depression Severity During Partial Hospitalization")+
  scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))+
  scale_y_continuous(name="Depression Severity",limits=c(15,40,by=5))+
  scale_color_manual(values=c("#BB9D00","red",
                              "darkred","orange"))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())+
  geom_vline(xintercept = 5,alpha =.25)+
  geom_vline(xintercept = 8,alpha =.25)+
  geom_vline(xintercept = 13,alpha =.25)+
  annotate("text", x = 5, y = 39, label = "Q1") +
  annotate("text", x = 8, y = 39, label = "Mean") +
  annotate("text", x = 13, y = 39, label = "Q3") 
```

## Depression Treatment Progress by Characteristics

#### Race
Duration 1-5 days
```{r}

#Create a New Data Set with an Average Depression Variable and Race
Mothership_Mean_CUDOS_Race<-Mothership_Long %>%
  filter(Duration == "1-5") %>%
  group_by(TxDay,Race_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

RaceDF1<-Mothership_Mean_CUDOS_Race[1:34,]
# plot
Race1<-ggplot(data=subset(RaceDF1,!is.na(Race_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Race_1,color=Race_1))+
  geom_line(size=1)+
  geom_point()+
  labs(
    title ="Depression Severity by Race During Partial Hospitalization",
    subtitle = "Patient discharge 1-5 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,40,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```

duration 6-10 days
```{r}

RaceDF2<-Mothership_Long %>%
  filter(Duration == "6-10") %>%
  group_by(TxDay,Race_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

RaceDF2<-RaceDF2[1:70,]

# plot
Race2<-ggplot(data=subset(RaceDF2,!is.na(Race_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Race_1,color=Race_1))+
  geom_line(size=1)+
  geom_point()+
  labs(
    title ="Depression Severity by Race During Partial Hospitalization",
    subtitle = "Patient discharge 6-10 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,40,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```
Discharge 10-15
```{r}
RaceDF3<-Mothership_Long %>%
  filter(Duration == "11-15") %>%
  group_by(TxDay,Race_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

RaceDF3<-RaceDF3[1:105,]

# plot
Race3<-ggplot(data=subset(RaceDF3,!is.na(Race_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Race_1,color=Race_1))+
  geom_line(size=1)+
  geom_point()+
  labs(title ="Depression Severity by Race During Partial Hospitalization",
    subtitle = "Patient discharge 11-15 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,40,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```

```{r}
RaceDF4<-Mothership_Long %>%
  filter(Duration == "16+") %>%
  group_by(TxDay,Race_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

RaceDF4<-RaceDF4[1:140,]

# plot
Race4<-ggplot(data=subset(RaceDF4,!is.na(Race_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Race_1,color=Race_1))+
  geom_line(size=1)+
  geom_point()+
  labs(title ="Depression Severity by Race During Partial Hospitalization",
    subtitle = "Patient discharge 16+ days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,40,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
Race4
```

#### putting them all together
```{r}
ggpubr::ggarrange(Race1,Race2,Race3,Race4,ncol=2,nrow=2)
```

## GENDER IDENTITY
Create a New Data Set with an Average Depression Variable and Gender
```{r}
#GENDER IDENTITY
#Create a New Data Set with an Average Depression Variable and Gender
Mothership_Mean_CUDOS_Gender<-Mothership_Long %>%
  group_by(TxDay,Gender_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

View(Mothership_Mean_CUDOS_Gender)

#Create the Depression Line Graph by Gender
ggplot(data=subset(Mothership_Mean_CUDOS_Gender,!is.na(Gender_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Gender_1,color=Gender_1))+
  geom_line(size=1)+
  geom_point()+
  ggtitle("Depression Severity by Gender During Partial Hospitalization")+
    #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,60,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```


Duration 1-5 days
```{r}

#Create a New Data Set with an Average Depression Variable and Gender
Mothership_Mean_CUDOS_Gender<-Mothership_Long %>%
  filter(Duration == "1-5") %>%
  group_by(TxDay,Gender_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))
GenderDF1<-Mothership_Mean_CUDOS_Gender[1:30,]
# plot
Gender1<-ggplot(data=subset(GenderDF1,!is.na(Gender_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Gender_1,color=Gender_1))+
  geom_line(size=1)+
  geom_point()+
  labs(
    title ="Depression Severity by Gender During Partial Hospitalization",
    subtitle = "Patient discharge 1-5 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,60,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```

duration 6-10 days
```{r}

GenderDF2<-Mothership_Long %>%
  filter(Duration == "6-10") %>%
  group_by(TxDay,Gender_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

GenderDF2<-GenderDF2[1:59,]

# plot
Gender2<-ggplot(data=subset(GenderDF2,!is.na(Gender_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Gender_1,color=Gender_1))+
  geom_line(size=1)+
  geom_point()+
  labs(
    title ="Depression Severity by Gender During Partial Hospitalization",
    subtitle = "Patient discharge 6-10 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,60,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```
Discharge 10-15
```{r}
GenderDF3<-Mothership_Long %>%
  filter(Duration == "11-15") %>%
  group_by(TxDay,Gender_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))

GenderDF3<-GenderDF3[1:90,]

# plot
Gender3<-ggplot(data=subset(GenderDF3,!is.na(Gender_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Gender_1,color=Gender_1))+
  geom_line(size=1)+
  geom_point()+
  labs(title ="Depression Severity by Gender During Partial Hospitalization",
    subtitle = "Patient discharge 11-15 days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,60,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
```

```{r}
GenderDF4<-Mothership_Long %>%
  filter(Duration == "16+") %>%
  group_by(TxDay,Gender_1) %>%
  summarise(mean_CUDOS=mean(CUDOS,na.rm=TRUE))
View(GenderDF4)
GenderDF4<-GenderDF4[1:120,]

# plot
Gender4<-ggplot(data=subset(GenderDF4,!is.na(Gender_1)),
       aes(x=TxDay,y=mean_CUDOS,group=Gender_1,color=Gender_1))+
  geom_line(size=1)+
  geom_point()+
  labs(title ="Depression Severity by Gender During Partial Hospitalization",
    subtitle = "Patient discharge 16+ days")+
  #scale_x_discrete(name="Treatment Day",limits=c(1,2,3,4,5,6,7,8,9,10))+
  scale_x_continuous(name="Depression Severity",limits=c(0,20,by=1))+
  scale_y_continuous(name="Depression Severity",limits=c(10,60,by=5))+
  scale_color_manual(values=c("#209845","#3D4A3E","#A0AFA1",
                              "#0098DB","#0065A3","darkgreen"))+
  theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  theme(legend.title=element_blank())
Gender4
```

```{r}
ggpubr::ggarrange(Gender1,Gender2,Gender3,Gender4,ncol=2,nrow=2)
```

