---
title: "Diagnosis_Vis"
output: html_document
date: "2023-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE,warning = FALSE)
# Libraries 
library(tidyverse)
library(dplyr)
library(haven)
library(ggplot2)
library(tidyr)
library("lubridate")

#Data
Mothership<-read.csv("~/Desktop/Coding/data/Mothership_Vis.csv")
Mothership<-mutate(Mothership,
      DC_status_1 = as.factor(DC_status_1),
      Education_1 = as.factor(Education_1),
      Gender_1 = as.factor(Gender_1),
      Relationship_1 = as.factor(Relationship_1),
      Sexuality_1 = as.factor(Sexuality_1),
      IPT_track_1 = as.factor(IPT_track_1),
      Race_1 = as.factor(Race_1),
      Education_1 = as.factor(Education_1),
      Duration = as.factor(Duration),
      )

Mothership$Intake_1<-ymd(Mothership$Intake_1,locale = "en_US.UTF-8")
Mothership$TxYear<-as.numeric(format(Mothership$Intake_1,"%Y"))
Mothership<-mutate(Mothership,
                   TxYear = as.factor(TxYear),
                   TxYear = recode(TxYear,
                                   "1582"="2014",
                                   "2021"="2020",
                                   "2022"="2020"))
```

## Create Diagnosis Variables 
```{r}
Mothership<-Mothership %>%
  mutate(
          # Mood Disorders
                     Mood_D = as.factor(
                      ifelse(
                        MDD_P ==1 | Bipolar1_P == 1 | Bipolar2_P == 1 | Dysthymia_P == 1, 1, 0)),
          # Anxiety Disorders
                    Anxiety_D = as.factor(
                      ifelse(
                        GAD_P ==1 | Panic_P == 1 | PanicAgor_P == 1 | Agoraphobia_P == 1 |
                        Social_P == 1 | Specific_P == 1, 1, 0)),
          # Obsessive Compusive Disorders
                #OCD_P is for current OCD
          # Personality Disorders
                #BPD_P is for current BPD
          # Substance Use Disorders
                    Substance_D = as.factor(
                      ifelse(
                        Alcohol_P == 1 | Drug_P ==1, 1, 0)),
          # Trauma or stresor related disorders
                    Trauma_D = as.factor(
                      ifelse(PTSD_P == 1 | Adjustment_P ==1, 1,0)),
          # Psychotic Disorders
                    Psychotic_D = as.factor(
                      ifelse(
                        Schiz_P == 1 | Schizaff_P == 1,1,0)),
            # Eating Disorders
                    Eating_D = as.factor(
                      ifelse(
                        Anorex_P == 1 | Bulim_P == 1 | Binge_P == 1, 1,0)),
            # Somatic Disroders
                    Somatic_D = as.factor(
                      ifelse(
                        Somat_P == 1 | UndiffSoma_P == 1| Hypochondriasis_P ==1,
                        1,0)),
                    Disorder_Type = as.factor(
                      ifelse(Anxiety_D == 1, "Anxiety",
                      ifelse(OCD_P == 1, "OCD",
                      ifelse(BPD_P == 1, "BPD",
                      ifelse(Substance_D == 1, "Substance Use",
                      ifelse(Trauma_D == 1, "Stress and Trauma",
                      ifelse(Mood_D == 1, "Mood",
                      ifelse(Psychotic_D == 1, "Psychotic", 
                      ifelse(Eating_D == 1, "Eating", 
                      ifelse(Somatic_D == 1, "Somatic", NA
                      )))))))))),
                  Anxiety_C =  as.factor(
                    ifelse(  GAD_C ==1 | Panic_C == 1 | PanicAgor_C == 1 | Agoraphobia_C == 1 |
                        Social_C == 1 | Specific_C == 1, 1, 0)),
                  Mood_C =  as.factor(
                    ifelse(MDD_C ==1 | Bipolar1_C == 1 | Bipolar2_C == 1 | Dysthymia_C == 1, 1, 0)),
                  Substance_C = as.factor(
                    ifelse(Alcohol_C == 1 | Drug_C ==1, 1, 0)),
                  Trauma_C = as.factor(
                    ifelse(PTSD_C == 1 | Adjustment_C ==1, 1,0)),
                  Psychotic_C = as.factor(
                    ifelse(Schiz_C == 1 | Schizaff_C == 1,1,0)),
                  Eating_C = as.factor(
                    ifelse(Anorex_C == 1 | Bulim_C == 1 | Binge_C == 1, 1,0)),
                  Somatic_C = as.factor(
                    ifelse(Somat_C == 1 | UndiffSoma_C == 1| Hypochondriasis_C ==1, 1,0)),
          #emotional disorders
                  Emotional_dis = as.factor(
                    ifelse(Anxiety_D == 1 | OCD_P == 1 | Trauma_D == 1 |
                           Mood_D == 1, "Emotional Disorder", "Other Disorder")),
                  Co_Anx = as.factor(
                        ifelse(Anxiety_D == 1 & Mood_C == 1 |
                                Anxiety_D == 1 & OCD_C == 1 |
                                Anxiety_D == 1 & BPD_C == 1 |
                                Anxiety_D == 1 & Substance_C == 1 |
                                Anxiety_D == 1 & Trauma_C == 1 |
                                Anxiety_D == 1 & Eating_C ==1 |
                                Anxiety_D == 1 & Psychotic_C ==1 |
                                Anxiety_D == 1 & Somatic_C ==1, 1, 0)),
                  Co_Mood = as.factor(
                        ifelse(Mood_D == 1 & Anxiety_C == 1 |
                                Mood_D == 1 & OCD_C == 1 |
                                Mood_D == 1 & BPD_C == 1 |
                                Mood_D == 1 & Substance_C == 1 |
                                Mood_D == 1 & Trauma_C == 1 |
                                Mood_D == 1 & Eating_C ==1 |
                                Mood_D == 1 & Psychotic_C ==1 |
                                Mood_D == 1 & Somatic_C ==1 , 1, 0)),
                  Co_OCD = as.factor(
                        ifelse(OCD_C == 1 & Anxiety_C == 1 |
                                OCD_C == 1 & Mood_C == 1 |
                                OCD_C == 1 & BPD_C == 1 |
                                OCD_C == 1 & Substance_C == 1 |
                                OCD_C == 1 & Trauma_C == 1 |
                                OCD_C == 1 & Eating_C ==1 |
                                OCD_C == 1 & Psychotic_C ==1 |
                                OCD_C == 1 & Somatic_C ==1, 1, 0)),
                  CO_BPD = as.factor(
                        ifelse(BPD_C == 1 & Anxiety_C == 1 |
                                BPD_C == 1 & Mood_C == 1 |
                                BPD_C == 1 & OCD_C == 1 |
                                BPD_C == 1 & Substance_C == 1 |
                                BPD_C == 1 & Trauma_C == 1 |
                                BPD_C == 1 & Eating_C ==1 |
                                BPD_C == 1 & Psychotic_C ==1 |
                                BPD_C == 1 & Somatic_C ==1 , 1, 0)),
                  CO_Psychotic = as.factor(
                       ifelse(Psychotic_D == 1 & Mood_C == 1 |
                                Psychotic_D == 1 & OCD_C == 1 |
                                Psychotic_D == 1 & BPD_C == 1 |
                                Psychotic_D == 1 & Substance_C == 1 |
                                Psychotic_D == 1 & Trauma_C == 1 |
                                Psychotic_D == 1 & Eating_C ==1 |
                                Psychotic_D == 1 & Anxiety_C ==1 |
                                Psychotic_D == 1 & Somatic_C ==1, 1, 0)),
                  CO_Eating = as.factor(
                      ifelse(Eating_D == 1 & Mood_C == 1 |
                                Eating_D == 1 & OCD_C == 1 |
                                Eating_D == 1 & BPD_C == 1 |
                                Eating_D == 1 & Substance_C == 1 |
                                Eating_D == 1 & Trauma_C == 1 |
                                Eating_D == 1 & Psychotic_C ==1 |
                                Eating_D == 1 & Anxiety_C ==1 |
                                Eating_D == 1 & Somatic_C ==1, 1, 0)),
                  CO_Somatic =  as.factor(
                       ifelse(Somatic_D == 1 & Mood_C == 1 |
                                Somatic_D == 1 & OCD_C == 1 |
                                Somatic_D == 1 & BPD_C == 1 |
                                Somatic_D == 1 & Substance_C == 1 |
                                Somatic_D == 1 & Trauma_C == 1 |
                                Somatic_D == 1 & Eating_C ==1 |
                                Somatic_D == 1 & Anxiety_C ==1 |
                                Somatic_D == 1 & Psychotic_C ==1, 1, 0)))
                      

##### df for plots 

# df without NAs in date and disorder type
Mothership_Diag <- Mothership %>%
  filter(!is.na(Disorder_Type))%>%
  filter(!is.na(TxYear))

# df with and without depression
No_depressy <- Mothership_Diag %>%
  filter(Disorder_Type != "Mood")
```


#### Amount of disorders treated
```{r}
#overall psychiatric disorders
ggplot(data = subset(Mothership_Diag, !is.na(Disorder_Type)),mapping = aes(x = Disorder_Type, fill=Disorder_Type))+
  geom_bar()+
  ggtitle("Frequency of Psychiatric Disorder Subtypes") +
  theme(axis.text.x = element_text(angle = 45,hjust = 1))+
  xlab("Psychiatric Disorder Subtype")+
  theme(panel.grid.major.x = element_line(color = "grey",size = 0.5,linetype = 2))+
  theme(panel.background=NULL)+
  scale_y_continuous(name = "Frequency",limits=c(0,3500))+
  coord_flip()
```



#### Number of disorders over time.
```{r}
# Libraries
library(ggplot2)
#install.packages("hrbrthemes")
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)


# Stacked
ggplot(data=subset(Mothership_Diag, !is.na(Disorder_Type)), 
       mapping= aes(x=TxYear, y = stat(count),
                    group=Disorder_Type, fill=Disorder_Type)) +
    geom_density(adjust=1.5,alpha=.4,position="fill") +
    theme(axis.text.x = element_text(angle = 45,hjust = 1))+
     theme(panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2))+
     xlab("Treatment Year") +
  theme(panel.background=NULL) +
    facet_wrap(~Emotional_dis)+
  labs(
    title = "Type of Disorders Treated at the Hospital Per Year",
    subtitle = "Broken Up By Disorder Types") +
    xlab("Treatment Year") +
    ylab("Percent of Patients With Disorder")
    
# Broken up by disorder. 
ggplot(data=subset(Mothership_Diag, !is.na(Disorder_Type)), 
    mapping= aes(x=TxYear,y = stat(count),
                 group=Disorder_Type, fill=Disorder_Type)) +
  geom_density(adjust=1.5,alpha=.6) +
  facet_wrap(~Disorder_Type)+
  theme_classic()+
    theme(
      panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2),
      axis.text.x = element_text(angle = 45,hjust = 1),
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank(),
      panel.background=NULL) +
  labs(
    title = "Type of Disorders Treated at the Hospital Per Year",
    subtitle = "Broken Up By Dmotional vs Other Disorders") +
    xlab("Treatment Year") +
    ylab("Number of Patients With Disorder")

```

```{r}
# without depression
ggplot(data=subset(No_depressy, !is.na(Disorder_Type)), 
    mapping= aes(x=TxYear,y = stat(count),
                 group=Disorder_Type, fill=Disorder_Type)) +
  geom_density(adjust=1.5,alpha=.6) +
  facet_wrap(~Disorder_Type)+
  theme_classic()+
    theme(
      panel.grid.major.y = element_line(color = "grey",size = 0.5,linetype = 2),
      axis.text.x = element_text(angle = 45,hjust = 1),
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      axis.ticks.x=element_blank(),
      panel.background=NULL) +
  labs(
    title = "Type of Disorders Treated at the Hospital Per Year",
    subtitle = "Broken Up By Dmotional vs Other Disorders") +
    xlab("Treatment Year") +
    ylab("Number of Patients With Disorder")
```

